// Licensed under the MIT license. See LICENSE file in the project root for full license information.

using System.Text;

namespace SqlQueryMapper
{
    /// <summary>
    /// The <see cref="SqlQuery"/> supports Streaming results, such as 
    /// a result generated by a "FOR JSON" clause. We need to configure 
    /// some options, when streaming the results.
    /// </summary>
    public class SqlQueryStreamOptions
    {
        /// <summary>
        /// Prefix, for example "{ \"data\": ".
        /// </summary>
        public string? Prefix { get; set; }

        /// <summary>
        /// Suffix, for example "}".
        /// </summary>
        public string? Suffix { get; set; }

        /// <summary>
        /// If no data was found, we may still need to return a default value. It is set to "[]" as 
        /// the default value, because we expect "FOR JSON" queries and not stream other data.
        /// </summary>
        public object DefaultOutput { get; set; } = "[]";

        /// <summary>
        /// The Encoding to be used for the Results, which is <see cref="Encoding.UTF8"/> 
        /// as a sane default value.
        /// </summary>
        public Encoding Encoding { get; set; } = Encoding.UTF8;
    }
}
